version: '3'

services:
    web:
        image: 'ultimatecharadesfrontend'
        networks:
            - g3tech
        expose:
            - 80:80
        environment:
            - VIRTUAL_HOST=ultimatecharades.g3tech.net
            - VIRTUAL_PORT=80
            - LETSENCRYPT_HOST=ultimatecharades.g3tech.net
    server:
        image: 'ultimatecharadesbackend'
        networks:
            - g3tech
        expose:
            - 8080:8080
        environment:
            - CORS_ORIGIN=https://ultimatecharades.g3tech.net
            - VIRTUAL_HOST=ultimatecharadesbackend.g3tech.net
            - VIRTUAL_PORT=8080
            - LETSENCRYPT_HOST=ultimatecharadesbackend.g3tech.net

networks:
    g3tech:
        name: g3tech
