version: '3'

services:
    web:
        image: hl-docker-registry.g3tech.net/ultimate-charades-frontend:latest
        container_name: ultimate-charades-frontend
        ports:
            - 1001:80
    server:
        image: hl-docker-registry.g3tech.net/ultimate-charades-backend:latest
        container_name: ultimate-charades-backend
        ports:
            - 1002:8080
        environment:
            - CORS_ORIGIN=https://ultimatecharades.g3tech.net

