version: '3'

services:
    web:
        image: ultimatecharadesfrontend
        container_name: ultimatecharadesfrontend
        ports:
            - 192.168.1.90:1001:80
    server:
        image: ultimatecharadesbackend
        container_name: ultimatecharadesbackend
        ports:
            - 192.168.1.90:1002:8080
        environment:
            - CORS_ORIGIN=https://ultimatecharades.g3tech.net

